In [1]:
import pandas as pd
from pathlib import Path

In [2]:
BASE_DIR = Path.cwd().parent

books = pd.read_csv(BASE_DIR / "data" / "raw" / "books.csv")
book_tags = pd.read_csv(BASE_DIR / "data" / "raw" / "book_tags.csv")
tags = pd.read_csv(BASE_DIR / "data" / "raw" / "tags.csv")

In [3]:
print("books:", books.shape)
print("book_tags:", book_tags.shape)
print("tags:", tags.shape)

books: (10000, 23)
book_tags: (999912, 3)
tags: (34252, 2)

In [6]:
books.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [5]:
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [7]:
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [8]:
print("=== BOOKS ===")
print(books.columns.tolist())

print("\n=== BOOK_TAGS ===")
print(book_tags.columns.tolist())

print("\n=== TAGS ===")
print(tags.columns.tolist())

=== BOOKS ===
['book_id', 'goodreads_book_id', 'best_book_id', 'work_id', 'books_count', 'isbn', 'isbn13', 'authors', 'original_publication_year', 'original_title', 'title', 'language_code', 'average_rating', 'ratings_count', 'work_ratings_count', 'work_text_reviews_count', 'ratings_1', 'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'image_url', 'small_image_url']

=== BOOK_TAGS ===
['goodreads_book_id', 'tag_id', 'count']

=== TAGS ===
['tag_id', 'tag_name']

In [9]:
print("=== BOOKS INFO ===")
books.info()

print("\n=== MISSING VALUE BOOKS ===")
print(books.isna().sum().sort_values(ascending=False))

=== BOOKS INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    10000 non-null  int64
 1   goodreads_book_id          10000 non-null  int64
 2   best_book_id               10000 non-null  int64
 3   work_id                    10000 non-null  int64
 4   books_count                10000 non-null  int64
 5   isbn                       9300 non-null   str
 6   isbn13                     9415 non-null   float64
 7   authors                    10000 non-null  str
 8   original_publication_year  9979 non-null   float64
 9   original_title             9415 non-null   str
 10  title                      10000 non-null  str
 11  language_code              8916 non-null   str
 12  average_rating             10000 non-null  float64
 13  ratings_count              10000 non-null  int64
 14  work_ratings_count         10000 non-null  int64
 15  work_text_reviews_count    10000 non-null  int64
 16  ratings_1                  10000 non-null  int64
 17  ratings_2                  10000 non-null  int64
 18  ratings_3                  10000 non-null  int64
 19  ratings_4                  10000 non-null  int64
 20  ratings_5                  10000 non-null  int64
 21  image_url                  10000 non-null  str
 22  small_image_url            10000 non-null  str
dtypes: float64(3), int64(13), str(7)
memory usage: 1.8 MB

=== MISSING VALUE BOOKS ===
language_code                1084
isbn                          700
isbn13                        585
original_title                585
original_publication_year      21
best_book_id                    0
book_id                         0
work_id                         0
books_count                     0
goodreads_book_id               0
authors                         0
title                           0
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
dtype: int64

In [10]:
print("=== DUPLICATE ===")
print("books:", books.duplicated().sum())
print("book_tags:", book_tags.duplicated().sum())
print("tags:", tags.duplicated().sum())

=== DUPLICATE ===
books: 0
book_tags: 6
tags: 0

In [11]:
books[
    [
        "book_id",
        "goodreads_book_id",
        "title",
        "authors",
        "original_publication_year",
        "average_rating",
        "ratings_count"
    ]
].head()

,book_id,goodreads_book_id,title,authors,original_publication_year,average_rating,ratings_count
0,1,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008.0,4.34,4780653
1,2,3,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",1997.0,4.44,4602479
2,3,41865,"Twilight (Twilight, #1)",Stephenie Meyer,2005.0,3.57,3866839
3,4,2657,To Kill a Mockingbird,Harper Lee,1960.0,4.25,3198671
4,5,4671,The Great Gatsby,F. Scott Fitzgerald,1925.0,3.89,2683664

In [12]:
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [13]:
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [14]:
print("Books unique Goodreads ID:", books["goodreads_book_id"].nunique())
print("Book tags unique Goodreads ID:", book_tags["goodreads_book_id"].nunique())
print("Unique tag ID:", tags["tag_id"].nunique())

Books unique Goodreads ID: 10000
Book tags unique Goodreads ID: 10000
Unique tag ID: 34252

In [16]:
books_ml = books[
    [
        "book_id",
        "goodreads_book_id",
        "title",
        "authors",
        "original_publication_year",
        "average_rating",
        "ratings_count"
    ]
].copy()

In [17]:
book_tags_named = book_tags.merge(
    tags,
    on="tag_id",
    how="left"
)

In [18]:
book_tags_named.head()

   goodreads_book_id  tag_id   count           tag_name
0                  1   30574  167697            to-read
1                  1   11305   37174            fantasy
2                  1   11557   34173          favorites
3                  1    8717   12986  currently-reading
4                  1   33114   12716        young-adult

In [19]:
book_tag_text = (
    book_tags_named
    .groupby("goodreads_book_id")["tag_name"]
    .apply(lambda x: " ".join(x.astype(str)))
    .reset_index()
)

In [20]:
book_tag_text = book_tag_text.rename(
    columns={"tag_name": "tags"}
)

In [21]:
book_tag_text.head()

   goodreads_book_id                                               tags
0                  1  to-read fantasy favorites currently-reading yo...
1                  2  to-read currently-reading fantasy favorites ch...
2                  3  to-read favorites fantasy currently-reading yo...
3                  5  favorites fantasy currently-reading young-adul...
4                  6  fantasy young-adult fiction harry-potter owned...

In [22]:
books_ml = books_ml.merge(
    book_tag_text,
    on="goodreads_book_id",
    how="left"
)

In [23]:
books_ml.head()

,book_id,goodreads_book_id,title,authors,original_publication_year,average_rating,ratings_count,tags
0,1,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008.0,4.34,4780653,favorites currently-reading young-adult fictio...
1,2,3,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",1997.0,4.44,4602479,to-read favorites fantasy currently-reading yo...
2,3,41865,"Twilight (Twilight, #1)",Stephenie Meyer,2005.0,3.57,3866839,young-adult fantasy favorites vampires ya fict...
3,4,2657,To Kill a Mockingbird,Harper Lee,1960.0,4.25,3198671,classics favorites to-read classic historical-...
4,5,4671,The Great Gatsby,F. Scott Fitzgerald,1925.0,3.89,2683664,classics favorites fiction classic books-i-own...

In [24]:
print(books_ml.shape)

(10000, 8)

In [25]:
books_ml.isna().sum()

book_id                       0
goodreads_book_id             0
title                         0
authors                       0
original_publication_year    21
average_rating                0
ratings_count                 0
tags                          0
dtype: int64

In [26]:
books_ml["title"] = books_ml["title"].fillna("")
books_ml["authors"] = books_ml["authors"].fillna("")
books_ml["tags"] = books_ml["tags"].fillna("")

In [28]:
books_ml["combined_text"] = (
    books_ml["title"] + " "
    + books_ml["authors"] + " "
    + books_ml["tags"]
)

In [29]:
books_ml[
    [
        "title",
        "authors",
        "tags",
        "combined_text"
    ]
].head(10)

,title,authors,tags,combined_text
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,favorites currently-reading young-adult fictio...,"The Hunger Games (The Hunger Games, #1) Suzann..."
1,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",to-read favorites fantasy currently-reading yo...,Harry Potter and the Sorcerer's Stone (Harry P...
2,"Twilight (Twilight, #1)",Stephenie Meyer,young-adult fantasy favorites vampires ya fict...,"Twilight (Twilight, #1) Stephenie Meyer young-..."
3,To Kill a Mockingbird,Harper Lee,classics favorites to-read classic historical-...,To Kill a Mockingbird Harper Lee classics favo...
4,The Great Gatsby,F. Scott Fitzgerald,classics favorites fiction classic books-i-own...,The Great Gatsby F. Scott Fitzgerald classics ...
5,The Fault in Our Stars,John Green,favorites to-read young-adult fiction ya roman...,The Fault in Our Stars John Green favorites to...
6,The Hobbit,J.R.R. Tolkien,fantasy favorites classics to-read fiction boo...,The Hobbit J.R.R. Tolkien fantasy favorites cl...
7,The Catcher in the Rye,J.D. Salinger,classics favorites fiction to-read classic you...,The Catcher in the Rye J.D. Salinger classics ...
8,"Angels & Demons (Robert Langdon, #1)",Dan Brown,to-read fiction mystery favorites thriller dan...,"Angels & Demons (Robert Langdon, #1) Dan Brow..."
9,Pride and Prejudice,Jane Austen,classics favorites fiction romance classic boo...,Pride and Prejudice Jane Austen classics favor...

In [30]:
books_ml.to_csv(
    "../data/processed/books_processed.csv",
    index=False
)

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

book_vectors = tfidf.fit_transform(
    books_ml["combined_text"]
)

print("Shape:", book_vectors.shape)

Shape: (10000, 10000)

In [5]:
print("Jumlah buku:", book_vectors.shape[0])
print("Jumlah fitur:", book_vectors.shape[1])
print("Jumlah non-zero:", book_vectors.nnz)

Jumlah buku: 10000
Jumlah fitur: 10000
Jumlah non-zero: 780214

In [6]:
import joblib

joblib.dump(
    tfidf,
    "../models/tfidf_vectorizer.joblib"
)

joblib.dump(
    book_vectors,
    "../models/book_vectors.joblib"
)

print("Model TF-IDF berhasil disimpan.")

Model TF-IDF berhasil disimpan.

In [7]:
from pathlib import Path

print(Path("../models/tfidf_vectorizer.joblib").exists())
print(Path("../models/book_vectors.joblib").exists())

True
True

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
similarity = cosine_similarity(
    book_vectors[0],
    book_vectors
)

print(similarity.shape)

(1, 10000)

In [10]:
import numpy as np

scores = similarity[0]

top_indices = np.argsort(scores)[::-1][:6]

for idx in top_indices:
    print(
        idx,
        books_ml.iloc[idx]["title"],
        round(scores[idx], 4)
    )

0 The Hunger Games (The Hunger Games, #1) 1.0
19 Mockingjay (The Hunger Games, #3) 0.9727
16 Catching Fire (The Hunger Games, #2) 0.966
506 The Hunger Games Trilogy Boxset (The Hunger Games, #1-3) 0.9352
1354 The Hunger Games Tribute Guide 0.7411
716 The Hunger Games: Official Illustrated Movie Companion 0.7157

In [11]:
user_interests = [
    "fantasy",
    "adventure",
    "magic"
]

user_text = " ".join(user_interests)

print(user_text)

fantasy adventure magic

In [12]:
user_vector = tfidf.transform([user_text])

print(user_vector.shape)

(1, 10000)

In [13]:
user_scores = cosine_similarity(
    user_vector,
    book_vectors
)[0]

print(user_scores.shape)

(10000,)

In [14]:
top_indices = np.argsort(user_scores)[::-1][:10]

for idx in top_indices:
    print(
        books_ml.iloc[idx]["title"],
        round(user_scores[idx], 4)
    )

Sandry's Book (Circle of Magic, #1) 0.4283
Before They Are Hanged (The First Law #2) 0.4043
Green Rider (Green Rider, #1) 0.4013
The Black Unicorn (Magic Kingdom of Landover, #2) 0.4012
Magic Kingdom For Sale/Sold (Magic Kingdom of Landover, #1) 0.3986
The Seeress of Kell (The Malloreon, #5) 0.3932
King of the Murgos (The Malloreon, #2) 0.3922
The Awakened Mage (Kingmaker, Kingbreaker, #2) 0.3903
Castle of Wizardry (The Belgariad, #4) 0.3878
The Diamond Throne (The Elenium, #1) 0.387

In [15]:
def recommend_books(user_interests, top_n=10):
    # Gabungkan minat user
    user_text = " ".join(user_interests)

    # Ubah minat user menjadi vector TF-IDF
    user_vector = tfidf.transform([user_text])

    # Hitung similarity dengan semua buku
    scores = cosine_similarity(
        user_vector,
        book_vectors
    )[0]

    # Ambil index dengan score tertinggi
    top_indices = np.argsort(scores)[::-1][:top_n]

    recommendations = []

    for idx in top_indices:
        recommendations.append({
            "book_id": books_ml.iloc[idx]["book_id"],
            "title": books_ml.iloc[idx]["title"],
            "score": round(float(scores[idx]), 4)
        })

    return recommendations

In [16]:
recommendations = recommend_books(
    ["fantasy", "adventure", "magic"],
    top_n=5
)

recommendations

[{'book_id': np.int64(4712),
  'title': "Sandry's Book (Circle of Magic, #1)",
  'score': 0.4283},
 {'book_id': np.int64(1230),
  'title': 'Before They Are Hanged (The First Law #2)',
  'score': 0.4043},
 {'book_id': np.int64(5414),
  'title': 'Green Rider (Green Rider, #1)',
  'score': 0.4013},
 {'book_id': np.int64(8275),
  'title': 'The Black Unicorn (Magic Kingdom of Landover, #2)',
  'score': 0.4012},
 {'book_id': np.int64(4190),
  'title': 'Magic Kingdom For Sale/Sold (Magic Kingdom of Landover, #1)',
  'score': 0.3986}]

In [17]:
def get_reason(user_interests, book_idx):
    book_text = str(books_ml.iloc[book_idx]["combined_text"]).lower()

    matched_interests = []

    for interest in user_interests:
        if interest.lower() in book_text:
            matched_interests.append(interest)

    if matched_interests:
        return "Sesuai dengan minat: " + ", ".join(matched_interests)

    return "Memiliki kemiripan dengan minat Anda"

In [18]:
def recommend_books(user_interests, top_n=10):
    user_text = " ".join(user_interests)

    user_vector = tfidf.transform([user_text])

    scores = cosine_similarity(
        user_vector,
        book_vectors
    )[0]

    top_indices = np.argsort(scores)[::-1][:top_n]

    recommendations = []

    for idx in top_indices:
        recommendations.append({
            "book_id": books_ml.iloc[idx]["book_id"],
            "title": books_ml.iloc[idx]["title"],
            "score": round(float(scores[idx]), 4),
            "reason": get_reason(user_interests, idx)
        })

    return recommendations

In [19]:
recommendations = recommend_books(
    ["fantasy", "adventure", "magic"],
    top_n=5
)

for rec in recommendations:
    print(rec)

{'book_id': np.int64(4712), 'title': "Sandry's Book (Circle of Magic, #1)", 'score': 0.4283, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(1230), 'title': 'Before They Are Hanged (The First Law #2)', 'score': 0.4043, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(5414), 'title': 'Green Rider (Green Rider, #1)', 'score': 0.4013, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(8275), 'title': 'The Black Unicorn (Magic Kingdom of Landover, #2)', 'score': 0.4012, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(4190), 'title': 'Magic Kingdom For Sale/Sold (Magic Kingdom of Landover, #1)', 'score': 0.3986, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}

In [20]:
def fallback_recommendations(top_n=10):
    popular_books = books_ml.sort_values(
        by=["ratings_count", "average_rating"],
        ascending=False
    ).head(top_n)

    recommendations = []

    for _, book in popular_books.iterrows():
        recommendations.append({
            "book_id": int(book["book_id"]),
            "title": book["title"],
            "score": None,
            "reason": "Direkomendasikan berdasarkan popularitas buku"
        })

    return recommendations

In [21]:
fallback = fallback_recommendations(top_n=5)

for rec in fallback:
    print(rec)

{'book_id': 1, 'title': 'The Hunger Games (The Hunger Games, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 2, 'title': "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)", 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 3, 'title': 'Twilight (Twilight, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 4, 'title': 'To Kill a Mockingbird', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 5, 'title': 'The Great Gatsby', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}

In [22]:
def get_recommendations(user_interests=None, top_n=10):
    if not user_interests:
        return fallback_recommendations(top_n)

    return recommend_books(
        user_interests,
        top_n
    )

In [23]:
result = get_recommendations(
    ["fantasy", "adventure", "magic"],
    top_n=5
)

for rec in result:
    print(rec)

{'book_id': np.int64(4712), 'title': "Sandry's Book (Circle of Magic, #1)", 'score': 0.4283, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(1230), 'title': 'Before They Are Hanged (The First Law #2)', 'score': 0.4043, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(5414), 'title': 'Green Rider (Green Rider, #1)', 'score': 0.4013, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(8275), 'title': 'The Black Unicorn (Magic Kingdom of Landover, #2)', 'score': 0.4012, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}
{'book_id': np.int64(4190), 'title': 'Magic Kingdom For Sale/Sold (Magic Kingdom of Landover, #1)', 'score': 0.3986, 'reason': 'Sesuai dengan minat: fantasy, adventure, magic'}

In [24]:
result = get_recommendations(
    [],
    top_n=5
)

for rec in result:
    print(rec)

{'book_id': 1, 'title': 'The Hunger Games (The Hunger Games, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 2, 'title': "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)", 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 3, 'title': 'Twilight (Twilight, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 4, 'title': 'To Kill a Mockingbird', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 5, 'title': 'The Great Gatsby', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}

In [25]:
result = get_recommendations(
    None,
    top_n=5
)

for rec in result:
    print(rec)

{'book_id': 1, 'title': 'The Hunger Games (The Hunger Games, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 2, 'title': "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)", 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 3, 'title': 'Twilight (Twilight, #1)', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 4, 'title': 'To Kill a Mockingbird', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}
{'book_id': 5, 'title': 'The Great Gatsby', 'score': None, 'reason': 'Direkomendasikan berdasarkan popularitas buku'}

In [26]:
test_cases = [
    ["fantasy", "magic"],
    ["romance", "love"],
    ["mystery", "crime"],
    ["science", "technology"],
]

In [27]:
for interests in test_cases:
    print("=" * 60)
    print("INTEREST:", interests)

    results = get_recommendations(
        interests,
        top_n=5
    )

    for i, rec in enumerate(results, start=1):
        print(
            f"{i}. {rec['title']} "
            f"(score={rec['score']}, "
            f"reason={rec['reason']})"
        )

============================================================
INTEREST: ['fantasy', 'magic']
1. Sandry's Book (Circle of Magic, #1) (score=0.4838, reason=Sesuai dengan minat: fantasy, magic)
2. The Black Unicorn (Magic Kingdom of Landover, #2) (score=0.4557, reason=Sesuai dengan minat: fantasy, magic)
3. Magic Kingdom For Sale/Sold (Magic Kingdom of Landover, #1) (score=0.4527, reason=Sesuai dengan minat: fantasy, magic)
4. The Awakened Mage (Kingmaker, Kingbreaker, #2) (score=0.4432, reason=Sesuai dengan minat: fantasy, magic)
5. Castle of Wizardry (The Belgariad, #4) (score=0.4399, reason=Sesuai dengan minat: fantasy, magic)
============================================================
INTEREST: ['romance', 'love']
1. Someone to Love (Someone to Love, #1) (score=0.4266, reason=Sesuai dengan minat: romance, love)
2. Accordance (Significance, #2) (score=0.4205, reason=Sesuai dengan minat: romance, love)
3. Endless Summer (The Boys Next Door, #1-2) (score=0.3792, reason=Sesuai dengan minat: romance, love)
4. From Ashes (From Ashes, #1) (score=0.354, reason=Sesuai dengan minat: romance, love)
5. Independence (Significance, #4) (score=0.3483, reason=Sesuai dengan minat: romance, love)
============================================================
INTEREST: ['mystery', 'crime']
1. The Interpretation of Murder (Freud, #1) (score=0.6242, reason=Sesuai dengan minat: mystery, crime)
2. Raven Black (Shetland Island, #1) (score=0.6122, reason=Sesuai dengan minat: mystery, crime)
3. The Lady in the Lake (Philip Marlowe, #4) (score=0.5852, reason=Sesuai dengan minat: mystery, crime)
4. The Blackhouse (Lewis Trilogy, #1) (score=0.5662, reason=Sesuai dengan minat: mystery, crime)
5. The Lewis Man (The Lewis Trilogy, #2) (score=0.5548, reason=Sesuai dengan minat: mystery, crime)
============================================================
INTEREST: ['science', 'technology']
1. Physics of the Future: How Science Will Shape Human Destiny and Our Daily Lives by the Year 2100 (score=0.4233, reason=Sesuai dengan minat: science, technology)
2. Chaos: Making a New Science (score=0.4209, reason=Sesuai dengan minat: science, technology)
3. The Structure of Scientific Revolutions (score=0.395, reason=Sesuai dengan minat: science, technology)
4. Physics of the Impossible: A Scientific Exploration into the World of Phasers, Force Fields, Teleportation, and Time Travel (score=0.3766, reason=Sesuai dengan minat: science, technology)
5. A Brief History of Time (score=0.3635, reason=Sesuai dengan minat: science, technology)

In [28]:
print("=" * 60)
print("FALLBACK TEST")

results = get_recommendations(
    [],
    top_n=5
)

for i, rec in enumerate(results, start=1):
    print(
        f"{i}. {rec['title']} "
        f"(score={rec['score']}, "
        f"reason={rec['reason']})"
    )

============================================================
FALLBACK TEST
1. The Hunger Games (The Hunger Games, #1) (score=None, reason=Direkomendasikan berdasarkan popularitas buku)
2. Harry Potter and the Sorcerer's Stone (Harry Potter, #1) (score=None, reason=Direkomendasikan berdasarkan popularitas buku)
3. Twilight (Twilight, #1) (score=None, reason=Direkomendasikan berdasarkan popularitas buku)
4. To Kill a Mockingbird (score=None, reason=Direkomendasikan berdasarkan popularitas buku)
5. The Great Gatsby (score=None, reason=Direkomendasikan berdasarkan popularitas buku)

In [29]:
results = get_recommendations(
    None,
    top_n=5
)

print(len(results))

5

In [30]:
for n in [1, 5, 10]:
    results = get_recommendations(
        ["fantasy", "magic"],
        top_n=n
    )

    print(
        f"top_n={n} → jumlah hasil={len(results)}"
    )

top_n=1 → jumlah hasil=1
top_n=5 → jumlah hasil=5
top_n=10 → jumlah hasil=10

In [31]:
communities = pd.DataFrame([
    {
        "community_id": "C001",
        "name": "Komunitas Pecinta Fantasy",
        "interests": "fantasy magic adventure",
        "city": "Tangerang Selatan",
        "province": "Banten",
        "verified": True
    },
    {
        "community_id": "C002",
        "name": "Klub Buku Romance",
        "interests": "romance love novel",
        "city": "Jakarta Selatan",
        "province": "DKI Jakarta",
        "verified": True
    },
    {
        "community_id": "C003",
        "name": "Komunitas Mystery & Crime",
        "interests": "mystery crime thriller",
        "city": "Tangerang Selatan",
        "province": "Banten",
        "verified": True
    },
    {
        "community_id": "C004",
        "name": "Book Club Sains",
        "interests": "science technology education",
        "city": "Bandung",
        "province": "Jawa Barat",
        "verified": True
    },
    {
        "community_id": "C005",
        "name": "Komunitas Literasi Umum",
        "interests": "reading literacy books",
        "city": "Tangerang Selatan",
        "province": "Banten",
        "verified": True
    }
])

communities

,community_id,name,interests,city,province,verified
0,C001,Komunitas Pecinta Fantasy,fantasy magic adventure,Tangerang Selatan,Banten,True
1,C002,Klub Buku Romance,romance love novel,Jakarta Selatan,DKI Jakarta,True
2,C003,Komunitas Mystery & Crime,mystery crime thriller,Tangerang Selatan,Banten,True
3,C004,Book Club Sains,science technology education,Bandung,Jawa Barat,True
4,C005,Komunitas Literasi Umum,reading literacy books,Tangerang Selatan,Banten,True

In [32]:
print("Jumlah komunitas:", len(communities))
print("Kolom:", communities.columns.tolist())
print()
print(communities[[
    "name",
    "interests",
    "city",
    "province",
    "verified"
]])

Jumlah komunitas: 5
Kolom: ['community_id', 'name', 'interests', 'city', 'province', 'verified']

                        name                     interests               city  \
0  Komunitas Pecinta Fantasy       fantasy magic adventure  Tangerang Selatan
1          Klub Buku Romance            romance love novel    Jakarta Selatan
2  Komunitas Mystery & Crime        mystery crime thriller  Tangerang Selatan
3            Book Club Sains  science technology education            Bandung
4    Komunitas Literasi Umum        reading literacy books  Tangerang Selatan

      province  verified
0       Banten      True
1  DKI Jakarta      True
2       Banten      True
3   Jawa Barat      True
4       Banten      True

In [33]:
community_vectors = tfidf.transform(
    communities["interests"]
)

print(community_vectors.shape)

(5, 10000)

In [34]:
def get_location_score(
    user_city,
    user_province,
    community_city,
    community_province
):
    if (
        user_city
        and community_city
        and user_city.lower() == community_city.lower()
    ):
        return 1.0

    if (
        user_province
        and community_province
        and user_province.lower() == community_province.lower()
    ):
        return 0.5

    return 0.0

In [35]:
def recommend_communities(
    user_interests,
    user_city=None,
    user_province=None,
    top_n=5
):
    user_text = " ".join(user_interests)

    user_vector = tfidf.transform([user_text])

    interest_scores = cosine_similarity(
        user_vector,
        community_vectors
    )[0]

    results = []

    for idx, community in communities.iterrows():

        location_score = get_location_score(
            user_city,
            user_province,
            community["city"],
            community["province"]
        )

        final_score = (
            0.7 * interest_scores[idx]
            + 0.3 * location_score
        )

        results.append({
            "community_id": community["community_id"],
            "name": community["name"],
            "interest_score": round(
                float(interest_scores[idx]), 4
            ),
            "location_score": location_score,
            "score": round(
                float(final_score), 4
            )
        })

    results.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return results[:top_n]

In [36]:
results = recommend_communities(
    user_interests=["fantasy", "magic"],
    user_city="Tangerang Selatan",
    user_province="Banten",
    top_n=5
)

for rec in results:
    print(rec)

{'community_id': 'C001', 'name': 'Komunitas Pecinta Fantasy', 'interest_score': 0.8486, 'location_score': 1.0, 'score': 0.894}
{'community_id': 'C003', 'name': 'Komunitas Mystery & Crime', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3}
{'community_id': 'C005', 'name': 'Komunitas Literasi Umum', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3}
{'community_id': 'C002', 'name': 'Klub Buku Romance', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0}
{'community_id': 'C004', 'name': 'Book Club Sains', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0}

In [39]:
def get_community_reason(
    user_interests,
    community,
    location_score
):
    matched_interests = []

    community_interests = str(
        community["interests"]
    ).lower()

    for interest in user_interests:
        if interest.lower() in community_interests:
            matched_interests.append(interest)

    reasons = []

    if matched_interests:
        reasons.append(
            "Sesuai dengan minat: "
            + ", ".join(matched_interests)
        )

    if location_score == 1.0:
        reasons.append("Berada di kota yang sama")
    elif location_score == 0.5:
        reasons.append("Berada di provinsi yang sama")

    if not reasons:
        return "Direkomendasikan berdasarkan kemiripan minat"

    return " dan ".join(reasons)

In [40]:
def recommend_communities(
    user_interests,
    user_city=None,
    user_province=None,
    top_n=5
):
    user_text = " ".join(user_interests)

    user_vector = tfidf.transform([user_text])

    interest_scores = cosine_similarity(
        user_vector,
        community_vectors
    )[0]

    results = []

    for idx, community in communities.iterrows():

        location_score = get_location_score(
            user_city,
            user_province,
            community["city"],
            community["province"]
        )

        final_score = (
            0.7 * interest_scores[idx]
            + 0.3 * location_score
        )

        reason = get_community_reason(
            user_interests,
            community,
            location_score
        )

        results.append({
            "community_id": community["community_id"],
            "name": community["name"],
            "interest_score": round(
                float(interest_scores[idx]), 4
            ),
            "location_score": location_score,
            "score": round(
                float(final_score), 4
            ),
            "reason": reason
        })

    results.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return results[:top_n]

In [41]:
results = recommend_communities(
    user_interests=["fantasy", "magic"],
    user_city="Tangerang Selatan",
    user_province="Banten",
    top_n=5
)

for rec in results:
    print(rec)

{'community_id': 'C001', 'name': 'Komunitas Pecinta Fantasy', 'interest_score': 0.8486, 'location_score': 1.0, 'score': 0.894, 'reason': 'Sesuai dengan minat: fantasy, magic dan Berada di kota yang sama'}
{'community_id': 'C003', 'name': 'Komunitas Mystery & Crime', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3, 'reason': 'Berada di kota yang sama'}
{'community_id': 'C005', 'name': 'Komunitas Literasi Umum', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3, 'reason': 'Berada di kota yang sama'}
{'community_id': 'C002', 'name': 'Klub Buku Romance', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0, 'reason': 'Direkomendasikan berdasarkan kemiripan minat'}
{'community_id': 'C004', 'name': 'Book Club Sains', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0, 'reason': 'Direkomendasikan berdasarkan kemiripan minat'}

In [42]:
# TEST 1
test_1 = recommend_communities(
    user_interests=["fantasy", "magic"],
    user_city="Tangerang Selatan",
    user_province="Banten",
    top_n=3
)

print("TEST 1")
for rec in test_1:
    print(rec)

TEST 1
{'community_id': 'C001', 'name': 'Komunitas Pecinta Fantasy', 'interest_score': 0.8486, 'location_score': 1.0, 'score': 0.894, 'reason': 'Sesuai dengan minat: fantasy, magic dan Berada di kota yang sama'}
{'community_id': 'C003', 'name': 'Komunitas Mystery & Crime', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3, 'reason': 'Berada di kota yang sama'}
{'community_id': 'C005', 'name': 'Komunitas Literasi Umum', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3, 'reason': 'Berada di kota yang sama'}

In [43]:
# TEST 2
test_2 = recommend_communities(
    user_interests=["fantasy", "magic"],
    user_city="Bandung",
    user_province="Jawa Barat",
    top_n=3
)

print("TEST 2")
for rec in test_2:
    print(rec)

TEST 2
{'community_id': 'C001', 'name': 'Komunitas Pecinta Fantasy', 'interest_score': 0.8486, 'location_score': 0.0, 'score': 0.594, 'reason': 'Sesuai dengan minat: fantasy, magic'}
{'community_id': 'C004', 'name': 'Book Club Sains', 'interest_score': 0.0, 'location_score': 1.0, 'score': 0.3, 'reason': 'Berada di kota yang sama'}
{'community_id': 'C002', 'name': 'Klub Buku Romance', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0, 'reason': 'Direkomendasikan berdasarkan kemiripan minat'}

In [44]:
# TEST 3
test_3 = recommend_communities(
    user_interests=["romance", "love"],
    user_city="Jakarta Selatan",
    user_province="DKI Jakarta",
    top_n=3
)

print("TEST 3")
for rec in test_3:
    print(rec)

TEST 3
{'community_id': 'C002', 'name': 'Klub Buku Romance', 'interest_score': 0.8709, 'location_score': 1.0, 'score': 0.9096, 'reason': 'Sesuai dengan minat: romance, love dan Berada di kota yang sama'}
{'community_id': 'C001', 'name': 'Komunitas Pecinta Fantasy', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0, 'reason': 'Direkomendasikan berdasarkan kemiripan minat'}
{'community_id': 'C003', 'name': 'Komunitas Mystery & Crime', 'interest_score': 0.0, 'location_score': 0.0, 'score': 0.0, 'reason': 'Direkomendasikan berdasarkan kemiripan minat'}